// prefix

const checkbox = {
  input: 'flex-shrink-0 appearance-none duration-200 ease-in-out cursor-pointer mr-1.5 outline-zero transition-shadow transition-colors border-solid form-border-checkbox form-border-color-input form-bg-input checked:form-bg-icon-check focus:form-ring',
  input_enabled: ' hover:form-shadow-input-hover hover:form-border-color-input-hover hover:form-bg-input-hover focus:form-shadow-input-focus checked:form-bg-primary checked:form-border-color-checked',
  input_disabled: 'form-bg-disabled form-border-color-input',
  input_danger: 'not-checked:form-border-color-input-danger not-checked:form-bg-input-danger',
  input_sm: 'form-w-checkbox-sm form-h-checkbox-sm form-rounded-checkbox-sm',
  input_md: 'form-w-checkbox form-h-checkbox form-rounded-checkbox',
  input_lg: 'form-w-checkbox-lg form-h-checkbox-lg form-rounded-checkbox-lg',
  $input: (classes, { isDisabled, Size, isDanger }) => ([
    classes.input,
    classes[`input_${Size}`],
    isDisabled ? classes.input_disabled : classes.input_enabled,
    !isDisabled && isDanger ? classes.input_danger : null,
  ]),
}

const radio = {
  input: 'flex items-center justify-center flex-shrink-0 appearance-none duration-200 ease-in-out cursor-pointer rounded-full mr-1.5 outline-zero transition-shadow transition-colors border-solid form-border-radio form-border-color-input form-bg-input checked:form-bg-icon-radio focus:form-ring',
  input_enabled: ' hover:form-shadow-input-hover hover:form-border-color-input-hover hover:form-bg-input-hover focus:form-shadow-input-focus checked:form-bg-primary checked:form-border-color-checked',
  input_disabled: 'form-bg-disabled form-border-color-input',
  input_danger: 'not-checked:form-border-color-input-danger not-checked:form-bg-input-danger',
  input_sm: 'form-w-checkbox-sm form-h-checkbox-sm',
  input_md: 'form-w-checkbox form-h-checkbox',
  input_lg: 'form-w-checkbox-lg form-h-checkbox-lg',
  $input: (classes, { isDisabled, Size, isDanger }) => ([
    classes.input,
    classes[`input_${Size}`],
    isDisabled ? classes.input_disabled : classes.input_enabled,
    !isDisabled && isDanger ? classes.input_danger : null,
  ]),
}

const text = {
  container: '',
  inputContainer: 'w-full flex flex-1 transition-colors transition-shadow border-solid form-border-input form-shadow-input group',
  inputContainer_sm: 'form-rounded-sm',
  inputContainer_md: 'form-rounded',
  inputContainer_lg: 'form-rounded-lg',
  inputContainer_enabled: 'form-bg-input form-color-input form-border-color-input hover:form-bg-input-hover hover:form-color-input-hover hover:form-border-color-input-hover hover:form-shadow-input-hover',
  inputContainer_disabled: 'form-bg-disabled form-color-disabled form-border-color-input',
  inputContainer_focused: 'form-bg-input-focus form-color-input-focus form-border-color-input-focus form-shadow-input-focus form-ring hover:form-shadow-input-hover',
  inputContainer_success: 'form-bg-input-success form-color-input-success form-border-color-input-success hover:form-shadow-input-hover',
  inputContainer_success_focused: 'form-shadow-input-focus form-ring',
  inputContainer_danger: 'form-bg-input-danger form-color-input-danger form-border-color-input-danger hover:form-shadow-input-hover',
  inputContainer_danger_focused: 'form-shadow-input-focus form-ring',
  input: 'w-full z-1 bg-transparent ',
  input_sm: 'form-p-input-sm form-text-sm form-h-input-height-sm',
  input_md: 'form-p-input form-text form-h-input-height',
  input_lg: 'form-p-input-lg form-text-lg form-h-input-height-lg with-floating:form-p-input-floating-lg',
  input_enabled: 'border-0 form-color-input group-hover:form-color-input-hover',
  input_disabled: 'form-color-disabled',
  input_focused: 'form-color-input-focus',
  input_success: 'form-color-input-success',
  input_danger: 'form-color-input-danger',
  $inputContainer: (classes, { isDisabled, Size, isSuccess, isDanger, focused }) => ([
    classes.inputContainer,
    classes[`inputContainer_${Size}`],
    isDisabled ? classes.inputContainer_disabled : null,
    !isDisabled && !isSuccess && !isDanger && !focused ? classes.inputContainer_enabled : null,
    !isDisabled && focused && !isSuccess && !isDanger ? classes.inputContainer_focused : null,
    !isDisabled && isDanger ? classes.inputContainer_danger : null,
    !isDisabled && isDanger && focused ? classes.inputContainer_danger_focused : null,
    !isDisabled && isSuccess ? classes.inputContainer_success : null,
    !isDisabled && isSuccess && focused ? classes.inputContainer_success_focused : null,
  ]),
  $input: (classes, { isDisabled, Size, isSuccess, isDanger, focused }) => ([
    classes.input,
    classes[`input_${Size}`],
    isDisabled ? classes.input_disabled : null,
    !isDisabled && !isSuccess && !isDanger && !focused  ? classes.input_enabled : null,
    !isDisabled && focused && !isSuccess && !isDanger ? classes.input_focused : null,
    !isDisabled && isDanger ? classes.input_danger : null,
    !isDisabled && isSuccess ? classes.input_success : null,
  ]),
}

const textarea = {
  ...text,
  inputContainer_sm: 'form-rounded-large-sm',
  inputContainer_md: 'form-rounded-large',
  inputContainer_lg: 'form-rounded-large-lg',
  input_sm: 'form-p-input-sm form-rounded-large-sm form-text-sm',
  input_md: 'form-p-input form-rounded-large form-text',
  input_lg: 'form-p-input-lg form-rounded-large-lg form-text-lg with-floating:form-p-input-floating-lg',
}

const editor = {
  container: '',
  input: 'border-solid form-border-input form-shadow-input',
  input_enabled: 'form-bg-input form-color-input form-border-color-input hover:form-bg-input-hover hover:form-color-input-hover hover:form-border-color-input-hover hover:form-shadow-input-hover',
  input_disabled: 'form-editor-disabled form-bg-disabled form-color-disabled',
  input_success: 'form-bg-input-success form-color-input-success form-border-color-input-success hover:form-shadow-input-hover',
  input_danger: 'form-bg-input-danger form-color-input-danger form-border-color-input-danger hover:form-shadow-input-hover',
  input_focused: 'form-color-input-focus form-border-color-input-focus form-bg-input-focus form-shadow-input-focus form-ring',
  input_focused_success: 'form-shadow-input-focus form-ring',
  input_focused_danger: 'form-shadow-input-focus form-ring',
  input_sm: 'form-rounded-large-sm form-editor-sm',
  input_md: ' form-rounded-large',
  input_lg: 'form-rounded-large-lg form-editor-lg',
  $input: (classes, { isDisabled, focused, Size, isSuccess, isDanger }) => ([
    classes.input,
    classes[`input_${Size}`],
    isDisabled ? classes.input_disabled : null,
    !isDisabled && !isSuccess && !isDanger && !focused ? classes.input_enabled : null,
    !isDisabled && isDanger ? classes.input_danger : null,
    !isDisabled && isSuccess ? classes.input_success : null,
    focused && !isDanger && !isSuccess ? classes.input_focused : null,
    focused && isSuccess ? classes.input_focused_success : null,
    focused && isDanger ? classes.input_focused_danger : null,
  ]),
}

const select = {
  container: 'relative mx-auto w-full flex items-center justify-end box-border cursor-pointer outline-zero transition-shadow transition-colors border-solid form-border-input form-shadow-input',
  container_enabled: 'form-bg-input form-color-input form-border-color-input focus:form-color-input-focus focus:form-border-color-input-focus focus:form-bg-input-focus hover:form-shadow-input-hover',
  container_disabled: 'form-bg-disabled form-color-disabled cursor-default',
  container_success: 'form-bg-input-success form-color-input-success form-border-color-input-success hover:form-shadow-input-hover',
  container_danger: 'form-bg-input-danger form-color-input-danger form-border-color-input-danger  hover:form-shadow-input-hover',
  container_sm: 'form-text-sm form-rounded-sm form-min-h-input-height-sm',
  container_md: 'form-text form-rounded form-min-h-input-height',
  container_lg: 'form-text-lg form-rounded-lg form-min-h-input-height-lg',
  containerDisabled: '',
  containerOpen: '!rounded-b-none',
  containerOpenTop: '!rounded-t-none',
  containerActive: 'form-shadow-input-focus form-ring',
  containerActive_enabled: 'form-bg-input-hover form-color-input-hover form-border-color-input-hover',
  search: 'w-full absolute inset-0 outline-zero appearance-none box-border border-0 font-sans bg-transparent form-color-input',
  search_sm: 'form-text-sm form-rounded-sm form-pl-input-sm',
  search_md: 'form-text form-rounded form-pl-input',
  search_lg: 'form-text-lg form-rounded-lg form-pl-input-lg with-floating:form-p-input-floating-lg',
  placeholder: 'flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent form-color-placeholder',
  placeholder_sm: 'form-pl-input-sm',
  placeholder_md: 'form-pl-input',
  placeholder_lg: 'form-pl-input-lg',
  caret: 'mask-bg mask-form-caret form-bg-icon w-2.5 h-4 py-px box-content relative z-10 flex-shrink-0 flex-grow-0 transition-transform transform pointer-events-none',
  caret_sm: 'form-mr-input-sm',
  caret_md: 'form-mr-input',
  caret_lg: 'form-mr-input-lg',
  caretOpen: 'rotate-180 pointer-events-auto',
  clear: 'relative z-10 opacity-50 transition duration-300 flex-shrink-0 flex-grow-0 flex hover:opacity-100',
  clear_sm: 'form-pr-input-sm',
  clear_md: 'form-pr-input',
  clear_lg: 'form-pr-input-lg',
  clearIcon: 'mask-bg mask-form-remove form-bg-icon w-2.5 h-4 py-px box-content inline-block',
  spinner: 'mask-bg mask-form-spinner form-bg-primary w-4 h-4 z-10 animate-spin flex-shrink-0 flex-grow-0',
  spinner_sm: 'form-mr-input-sm',
  spinner_md: 'form-mr-input',
  spinner_lg: 'form-mr-input-lg',
  dropdown: 'max-h-60 absolute -left-px -right-px bottom-0 transform translate-y-full form-border-dropdown border-solid form-border-color-input form-bg-input -mt-px overflow-y-scroll z-50 flex flex-col',
  dropdown_sm: 'form-rounded-b-sm',
  dropdown_md: 'form-rounded-b',
  dropdown_lg: 'form-rounded-b-lg',
  dropdownTop: '-translate-y-full top-px bottom-auto flex-col-reverse !rounded-b-none',
  dropdownTop_sm: 'form-rounded-t-sm',
  dropdownTop_md: 'form-rounded-t',
  dropdownTop_lg: 'form-rounded-t-lg',
  dropdownHidden: 'hidden',
  options: 'flex flex-col p-0 m-0 list-none form-color-input',
  optionsTop: 'flex-col-reverse',
  group: 'p-0 m-0',
  groupLabel: 'flex box-border items-center justify-start text-left form-py-0.5input font-semibold form-bg-selected form-color-input filter brightness-90 cursor-default',
  groupLabel_sm: 'form-px-input-sm form-text-small-sm',
  groupLabel_md: 'form-px-input form-text-small',
  groupLabel_lg: 'form-px-input-lg form-text-small-lg',
  groupLabelPointable: 'cursor-pointer',
  groupLabelPointed: 'brightness-95',
  groupLabelSelected: 'form-bg-primary-darker !form-color-on-primary brightness-100',
  groupLabelDisabled: 'form-bg-disabled form-color-disabled cursor-not-allowed',
  groupLabelSelectedPointed: 'form-bg-primary-darker !form-color-on-primary brightness-100 opacity-90',
  groupLabelSelectedDisabled: 'form-bg-primary-darker !form-color-on-primary brightness-100 opacity-50 cursor-not-allowed',
  groupOptions: 'p-0 m-0',
  option: 'flex items-center justify-start box-border text-left cursor-pointer',
  option_sm: 'form-px-input-sm form-py-input-border-sm',
  option_md: 'form-px-input form-py-input-border',
  option_lg: 'form-px-input-lg form-py-input-border-lg',
  optionPointed: 'form-color-input form-bg-selected',
  optionSelected: 'form-bg-primary form-color-on-primary',
  optionDisabled: 'form-color-disabled cursor-not-allowed',
  optionSelectedPointed: 'form-color-on-primary form-bg-primary opacity-90',
  optionSelectedDisabled: 'form-color-on-primary form-bg-primary opacity-50 cursor-not-allowed',
  fakeInput: 'bg-transparent absolute left-0 right-0 -bottom-px w-full h-px border-0 p-0 appearance-none outline-zero text-transparent',
  spacer: 'box-content',
  spacer_sm: 'form-h-input-height-inner-sm',
  spacer_md: 'form-h-input-height-inner',
  spacer_lg: 'form-h-input-height-inner-lg',
  noOptions: 'form-color-muted',
  noOptions_sm: 'form-p-input-sm',
  noOptions_md: 'form-p-input',
  noOptions_lg: 'form-p-input-lg',
  noResults: 'form-color-muted',
  noResults_sm: 'form-p-input-sm',
  noResults_md: 'form-p-input',
  noResults_lg: 'form-p-input-lg',
  $container: (classes, { Size, isDanger, isSuccess, isDisabled }) => ([
    classes.select.container,
    classes.select[`container_${Size}`],
    isDisabled ? classes.select.container_disabled : null,
    !isDisabled && !isSuccess && !isDanger ? classes.select.container_enabled : null,
    !isDisabled && isDanger ? classes.select.container_danger : null,
    !isDisabled && isSuccess ? classes.select.container_success : null,
  ]),
  $containerActive: (classes, { Size, isDanger, isSuccess, isDisabled }) => ([
    classes.select.containerActive,
    classes.select[`container_${Size}`],
    !isDisabled && !isSuccess && !isDanger ? classes.select.containerActive_enabled : null,
  ]),
  $search: (classes, { Size }) => ([
    classes.select.search,
    classes.select[`search_${Size}`],
  ]),
  $placeholder: (classes, { Size }) => ([
    classes.select.placeholder,
    classes.select[`placeholder_${Size}`],
  ]),
  $caret: (classes, { Size }) => ([
    classes.select.caret,
    classes.select[`caret_${Size}`],
  ]),
  $clear: (classes, { Size }) => ([
    classes.select.clear,
    classes.select[`clear_${Size}`],
  ]),
  $spinner: (classes, { Size }) => ([
    classes.select.spinner,
    classes.select[`spinner_${Size}`],
  ]),
  $dropdown: (classes, { Size }) => ([
    classes.select.dropdown,
    classes.select[`dropdown_${Size}`],
  ]),
  $dropdownTop: (classes, { Size }) => ([
    classes.select.dropdownTop,
    classes.select[`dropdownTop_${Size}`],
  ]),
  $groupLabel: (classes, { Size }) => ([
    classes.select.groupLabel,
    classes.select[`groupLabel_${Size}`],
  ]),
  $option: (classes, { Size }) => ([
    classes.select.option,
    classes.select[`option_${Size}`],
  ]),
  $spacer: (classes, { Size }) => ([
    classes.select.spacer,
    classes.select[`spacer_${Size}`],
  ]),
  $noOptions: (classes, { Size }) => ([
    classes.select.noOptions,
    classes.select[`noOptions_${Size}`],
  ]),
  $noResults: (classes, { Size }) => ([
    classes.select.noResults,
    classes.select[`noResults_${Size}`],
  ]),
}

const groupTabs = {
  container: 'flex align-start cursor-pointer',
  wrapper: 'flex items-center justify-center py-1.5 w-full border-solid form-border-input',
  wrapper_not_last: '!border-r-0',
  wrapper_first: '',
  wrapper_first_sm: 'form-rounded-l-sm',
  wrapper_first_md: 'form-rounded-l',
  wrapper_first_lg: 'form-rounded-l-lg',
  wrapper_last: '',
  wrapper_last_sm: 'form-rounded-r-sm',
  wrapper_last_md: 'form-rounded-r',
  wrapper_last_lg: 'form-rounded-r-lg',
  wrapper_selected: 'form-bg-primary form-color-on-primary border-black border-opacity-15',
  wrapper_unselected: 'form-bg-input form-color-input form-border-color-input hover:form-bg-input-hover hover:form-color-input-hover',
  wrapper_disabled: 'opacity-50',
  wrapper_sm: 'form-p-input-sm form-text-sm',
  wrapper_md: 'form-p-input form-text',
  wrapper_lg: 'form-p-input-lg form-text-lg',
  input: 'hidden',
  text: '',
}

const groupBlocks = {
  container: 'flex align-start cursor-pointer',
  wrapper: 'flex items-center w-full border-solid form-border-input form-border-color-input form-color-input',
  wrapper_not_last: '!border-b-0',
  wrapper_first: '',
  wrapper_first_sm: 'form-rounded-large-t-sm',
  wrapper_first_md: 'form-rounded-large-t',
  wrapper_first_lg: 'form-rounded-large-t-lg',
  wrapper_last: '',
  wrapper_last_sm: 'form-rounded-large-b-sm',
  wrapper_last_md: 'form-rounded-large-b',
  wrapper_last_lg: 'form-rounded-large-b-lg',
  wrapper_selected: 'form-bg-selected',
  wrapper_unselected: 'form-bg-input',
  wrapper_disabled: 'opacity-50',
  wrapper_sm: 'px-4 py-2.5 form-text-sm',
  wrapper_md: 'px-4 py-3 form-text',
  wrapper_lg: 'px-4 py-3.5 form-text-lg',
  text_wrapper: 'ml-2',
  text: '',
  description: 'form-color-muted',
  description_sm: 'form-text-small-sm -mt-0.5',
  description_md: 'form-text-small -mt-0.5',
  description_lg: 'form-text-small-lg -mt-0.5',
}

export default {
  // Elements
  ButtonElement: {
    container: '',
    button: 'inline-block transition form-border-btn form-shadow-btn focus:outline-zero',
    button_enabled: 'cursor-pointer transition-transform ease-linear focus:form-ring transform hover:scale-105',
    button_disabled: 'opacity-60 cursor-not-allowed',
    button_loading: 'form-color-transparent opacity-60 cursor-not-allowed',
    button_loading_primary: 'form-bg-spinner-on-primary',
    button_loading_secondary: 'form-bg-spinner-btn-secondary',
    button_loading_danger: 'form-bg-spinner-white',
    button_primary: 'form-bg-btn form-color-btn form-border-color-btn',
    button_secondary: 'form-bg-btn-secondary form-color-btn-secondary form-border-color-btn-secondary',
    button_danger: 'form-bg-btn-danger form-color-btn-danger form-border-color-btn-danger',
    button_sm: 'form-p-btn-sm form-rounded-btn-sm form-text-sm',
    button_md: 'form-p-btn form-rounded-btn form-text',
    button_lg: 'form-p-btn-lg form-rounded-btn-lg form-text-lg',
    $button: (classes, { isDisabled, isLoading, buttonClass, Size, danger, secondary }) => ([
      classes.button,
      danger ? classes.button_danger : null,
      secondary ? classes.button_secondary : null,
      !danger && !secondary ? classes.button_primary : null,
      classes[`button_${Size}`],
      isDisabled ? classes.button_disabled : null,
      !isDisabled && !isLoading ? classes.button_enabled : null,
      isLoading ? classes.button_loading : null,
      isLoading && danger ? classes.button_loading_danger : null,
      isLoading && secondary ? classes.button_loading_secondary : null,
      isLoading && !secondary && !danger ? classes.button_loading_primary : null,
      buttonClass,
    ]),
  },
  CheckboxElement: {
    ...checkbox,
    container: '',
    wrapper: 'flex align-start',
    wrapper_sm: 'form-pt-input-border-sm form-text-sm',
    wrapper_md: 'form-pt-input-border form-text',
    wrapper_lg: 'form-pt-input-border-lg form-text-lg',
    input: checkbox.input + ' form-shadow-input',
    input_sm: checkbox.input_sm + ' mt-0.75',
    input_md: checkbox.input_md + ' mt-1',
    input_lg: checkbox.input_lg + ' mt-1',
    text: 'cursor-pointer',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
    ]),
  },
  CheckboxgroupElement: {
    container: '',
    wrapper: 'flex flex-col justify-start',
    wrapper_sm: 'form-pt-input-border-sm',
    wrapper_md: 'form-pt-input-border',
    wrapper_lg: 'form-pt-input-border-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  CheckboxgroupElement_tabs: {
    container: '',
    wrapper: 'grid grid-flow-col form-shadow-input',
    wrapper_sm: 'form-rounded-large-sm',
    wrapper_md: 'form-rounded-large',
    wrapper_lg: 'form-rounded-large-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  CheckboxgroupElement_blocks: {
    container: '',
    wrapper: 'flex flex-col justify-start form-shadow-input',
    wrapper_sm: 'form-rounded-large-sm',
    wrapper_md: 'form-rounded-large',
    wrapper_lg: 'form-rounded-large-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  DateElement: {
    ...text,
  },
  DatesElement: {
    ...text,
  },
  EditorElement: {
    ...editor,
  },
  FileElement: {
    container: '',
    container_removing: 'opacity-50',
    button: 'form-border-btn form-shadow-btn inline-block transition focus:outline-zero',
    button_enabled: 'form-bg-btn-secondary form-color-btn-secondary form-border-color-btn-secondary cursor-pointer transition-transform transform hover:scale-105 focus:form-ring',
    button_disabled: 'opacity-50 cursor-not-allowed',
    button_sm: 'form-p-btn-sm form-rounded-btn-sm form-text-sm',
    button_md: 'form-p-btn form-rounded-btn form-text',
    button_lg: 'form-p-btn-lg form-rounded-btn-lg form-text-lg',
    $container: (classes, { removing }) => ([
      classes.container,
      removing ? classes.container_removing : null,
    ]),
    $button: (classes, { isDisabled, preparing, Size }) => ([
      classes.button,
      classes[`button_${Size}`],
      !isDisabled && !preparing ? classes.button_enabled : null,
      isDisabled || preparing ? classes.button_disabled : null,
    ]),
  },
  GroupElement: {
    container: '',
    wrapper: 'grid grid-cols-12',
    wrapper_sm: 'form-gap-y-gutter-sm form-gap-x-gutter-sm',
    wrapper_md: 'form-gap-y-gutter form-gap-x-gutter',
    wrapper_lg: 'form-gap-y-gutter-lg form-gap-x-gutter-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  ListElement: {
    container: '',
    list: 'grid',
    list_sm: 'form-gap-y-gutter-sm',
    list_md: 'form-gap-y-gutter',
    list_lg: 'form-gap-y-gutter-lg',
    list_disabled: '',
    list_sorting: '',
    listItem: 'relative group ghost:opacity-60',
    handle: 'absolute left-0 top-0 z-10 transform -translate-x-full cursor-grab active:cursor-grabbing opacity-0 transition group-hover:opacity-100',
    handle_sm: 'form-w-input-height-sm form-h-input-height-sm',
    handle_md: 'form-w-input-height form-h-input-height',
    handle_lg: 'form-w-input-height-lg form-h-input-height-lg',
    handleIcon: 'mask-bg mask-form-sort-handle form-bg-passive-color mask-size-2.8 block w-full h-full',
    remove: 'absolute z-1 w-4 h-4 box-content p-0.5 top-px left-0 form-bg-passive rounded-full transform -translate-x-1/2 -translate-y-1/2 transition opacity-0 filter hover:brightness-90 group-hover:opacity-100',
    removeIcon: 'mask-bg mask-form-remove-light form-bg-passive-color mask-size-3 block w-full h-full',
    add: 'inline-block form-bg-primary form-border-btn form-border-color-primary form-color-on-primary form-shadow-btn ease-linear transition-transform transform hover:scale-105 focus:form-ring',
    add_sm: 'form-mt-gutter-sm form-rounded-small-sm form-text-small-sm form-p-btn-small-sm',
    add_md: 'form-mt-gutter form-rounded-small form-text-small form-p-btn-small',
    add_lg: 'form-mt-gutter-lg form-rounded-small-lg form-text-small-lg form-p-btn-small-lg',
    $list: (classes, { isDisabled, sorting, Size }) => ([
      classes.list,
      classes[`list_${Size}`],
      isDisabled ? classes.list_disabled : null,
      sorting ? classes.list_sorting : null,
    ]),
    $handle: (classes, { Size }) => ([
      classes.handle,
      classes[`handle_${Size}`],
    ]),
    $add: (classes, { Size }) => ([
      classes.add,
      classes[`add_${Size}`],
    ]),
  },
  LocationElement: {
    ...text,
  },
  MultifileElement: {
    container: '',
    list: '',
    list_sm: 'form-mt-0.5gutter-sm',
    list_md: 'form-mt-0.5gutter',
    list_lg: 'form-mt-0.5gutter-lg',
    list_file: 'grid',
    list_file_sm: 'form-gap-y-0.5gutter-sm',
    list_file_md: 'form-gap-y-0.5gutter',
    list_file_lg: 'form-gap-y-0.5gutter-lg',
    list_image: 'grid',
    list_image_sm: 'form-gap-y-0.5gutter-sm',
    list_image_md: 'form-gap-y-0.5gutter',
    list_image_lg: 'form-gap-y-0.5gutter-lg',
    list_gallery: 'flex flex-wrap',
    list_gallery_sm: '',
    list_gallery_md: '',
    list_gallery_lg: '',
    list_disabled: '',
    list_sorting: '',
    listItem: 'relative group ghost:opacity-60',
    listItem_file: '',
    listItem_file_sm: '',
    listItem_file_md: '',
    listItem_file_lg: '',
    listItem_image: '',
    listItem_image_sm: '',
    listItem_image_md: '',
    listItem_image_lg: '',
    listItem_gallery: '',
    listItem_gallery_sm: 'form-mr-0.5gutter-sm form-mb-0.5gutter-sm',
    listItem_gallery_md: 'form-mr-0.5gutter form-mb-0.5gutter',
    listItem_gallery_lg: 'form-mr-0.5gutter-lg form-mb-0.5gutter-lg',
    handle: '',
    handle_file: 'absolute left-4 top-0 transform -translate-x-full cursor-grab active:cursor-grabbing opacity-0 transition group-hover:opacity-100',
    handle_file_sm: 'form-w-input-height-sm form-h-input-height-sm',
    handle_file_md: 'form-w-input-height form-h-input-height',
    handle_file_lg: 'form-w-input-height-lg form-h-input-height-lg',
    handle_image: 'absolute left-4 top-0 transform -translate-x-full cursor-grab active:cursor-grabbing opacity-0 transition group-hover:opacity-100',
    handle_image_sm: 'form-w-input-height-sm form-h-input-height-sm',
    handle_image_md: 'form-w-input-height form-h-input-height',
    handle_image_lg: 'form-w-input-height-lg form-h-input-height-lg',
    handle_gallery: 'absolute w-4 h-4 box-content top-0.5 left-0.5 mt-px ml-px form-bg-passve bg-center bg-no-repeat rounded-full transition opacity-0 group-hover:opacity-100 cursor-grab active:cursor-grabbing filter hover:brightness-90',
    handle_gallery_sm: '',
    handle_gallery_md: '',
    handle_gallery_lg: '',
    handleIcon: '',
    handleIcon_file: 'mask-bg mask-form-sort-handle bg-black mask-size-2.8 block w-full h-full',
    handleIcon_image: 'mask-bg mask-form-sort-handle bg-black mask-size-2.8 block w-full h-full',
    handleIcon_gallery: 'mask-bg mask-form-arrows form-bg-passive-color mask-size-3 block w-full h-full',
    dnd: '',
    dnd_sm: '',
    dnd_md: '',
    dnd_lg: '',
    button: 'inline-block transition form-border-btn focus:outline-zero',
    button_enabled: 'form-bg-btn-secondary form-color-btn-secondary form-border-color-btn-secondary form-shadow-btn cursor-pointer transition-transform transform hover:scale-105 focus:form-ring',
    button_disabled: 'opacity-50 cursor-not-allowed',
    button_sm: 'form-p-btn-sm form-rounded-btn-sm form-text-sm',
    button_md: 'form-p-btn form-rounded-btn form-text',
    button_lg: 'form-p-btn-lg form-rounded-btn-lg form-text-lg',
    $list: (classes, { isDisabled, sorting, view, Size }) => ([
      classes.list,
      classes[`list_${Size}`],
      isDisabled ? classes.list_disabled : null,
      sorting ? classes.list_sorting : null,
      classes[`list_${view}`],
      classes[`list_${view}_${Size}`],
    ]),
    $listItem: (classes, { view, Size }) => ([
      classes.listItem,
      classes[`listItem_${view}`],
      classes[`listItem_${view}_${Size}`],
    ]),
    $handle: (classes, { view, Size }) => ([
      classes.handle,
      classes[`handle_${view}`],
      classes[`handle_${view}_${Size}`],
    ]),
    $handleIcon: (classes, { view }) => ([
      classes.handleIcon,
      classes[`handleIcon_${view}`],
    ]),
    $dnd: (classes, { Size }) => ([
      classes.dnd,
      classes[`dnd_${Size}`],
    ]),
    $button: (classes, { isDisabled, preparing, Size }) => ([
      classes.button,
      classes[`button_${Size}`],
      !isDisabled && !preparing ? classes.button_enabled : null,
      isDisabled || preparing ? classes.button_disabled : null,
    ]),
  },
  MultiselectElement: {
    container: '',
    input: 'w-full form-p-input transition-colors transition-shadow border-solid form-border-input form-shadow-input',
    input_enabled: 'form-bg-input form-color-input form-border-color-input hover:form-bg-input-hover hover:form-color-input-hover hover:form-border-color-input-hover focus:form-color-input-focus focus:form-border-color-input-focus focus:form-bg-input-focus hover:form-shadow-input-hover focus:form-shadow-input-focus focus:form-ring',
    input_disabled: 'form-bg-disabled form-color-disabled',
    input_success: 'form-bg-input-success form-color-input-success form-border-color-input-success hover:form-shadow-input-hover focus:form-shadow-input-focus focus:form-ring',
    input_danger: 'form-bg-input-danger form-color-input-danger form-border-color-input-danger hover:form-shadow-input-hover focus:form-shadow-input-focus focus:form-ring',
    input_sm: 'form-p-input-sm form-rounded-large-sm form-text-sm',
    input_md: 'form-p-input form-rounded-large form-text',
    input_lg: 'form-p-input-lg form-rounded-large-lg form-text-lg with-floating:form-p-input-floating-lg',
    inputWrapper: '',
    select: {
      ...select,
      multipleLabel: 'flex items-center h-full absolute left-0 top-0 pointer-events-none bg-transparent',
      multipleLabel_sm: 'form-pl-input-sm form-pr-select-label-sm',
      multipleLabel_md: 'form-pl-input form-pr-select-label',
      multipleLabel_lg: 'form-pl-input-lg form-pr-select-label-lg with-floating:form-p-input-floating-lg',
      $multipleLabel: (classes, { Size }) => ([
        classes.select.multipleLabel,
        classes.select[`multipleLabel_${Size}`],
      ]),
    },
    $input: (classes, { isDisabled, Size, isDanger, isSuccess }) => ([
      classes.input,
      classes[`input_${Size}`],
      isDisabled ? classes.input_disabled : null,
      !isDisabled && !isSuccess && !isDanger ? classes.input_enabled : null,
      !isDisabled && isDanger ? classes.input_danger : null,
      !isDisabled && isSuccess ? classes.input_success : null,
    ]),
  },
  ObjectElement: {
    container: '',
    wrapper: 'grid grid-cols-12',
    wrapper_sm: 'form-gap-y-gutter-sm form-gap-x-gutter-sm',
    wrapper_md: 'form-gap-y-gutter form-gap-x-gutter',
    wrapper_lg: 'form-gap-y-gutter-lg form-gap-x-gutter-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  RadioElement: {
    ...radio,
    container: '',
    wrapper: 'flex align-start form-pt-input-border',
    text: 'cursor-pointer',
    input: radio.input + ' form-shadow-input',
    input_sm: radio.input_sm + ' mt-0.75',
    input_md: radio.input_md + ' mt-1',
    input_lg: radio.input_lg + ' mt-1',
  },
  RadiogroupElement: {
    container: '',
    wrapper: 'flex flex-col justify-start',
    wrapper_sm: 'form-pt-input-border-sm',
    wrapper_md: 'form-pt-input-border',
    wrapper_lg: 'form-pt-input-border-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  RadiogroupElement_tabs: {
    container: '',
    wrapper: 'grid grid-flow-col grid form-shadow-input',
    wrapper_sm: 'form-rounded-large-sm',
    wrapper_md: 'form-rounded-large',
    wrapper_lg: 'form-rounded-large-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  RadiogroupElement_blocks: {
    container: '',
    wrapper: 'flex flex-col justify-start form-shadow-input',
    wrapper_sm: 'form-rounded-large-sm',
    wrapper_md: 'form-rounded-large',
    wrapper_lg: 'form-rounded-large-lg',
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`]
    ]),
  },
  SelectElement: {
    container: '',
    input: 'w-full transition-colors transition-shadow border-solid form-border-input form-shadow-input',
    input_enabled: 'form-bg-input form-color-input form-border-color-input hover:form-bg-input-hover hover:form-color-input-hover hover:form-border-color-input-hover focus:form-color-input-focus focus:form-border-color-input-focus focus:form-bg-input-focus hover:form-shadow-input-hover focus:form-shadow-input-focus focus:form-ring',
    input_disabled: 'form-bg-disabled form-color-disabled',
    input_success: 'form-bg-input-success form-color-input-success form-border-color-input-success hover:form-shadow-input-hover focus:form-shadow-input-focus focus:form-ring',
    input_danger: 'form-bg-input-danger form-color-input-danger form-border-color-input-danger hover:form-shadow-input-hover focus:form-shadow-input-focus focus:form-ring',
    input_sm: 'form-p-input-sm form-rounded-sm form-text-sm',
    input_md: 'form-p-input form-rounded form-text',
    input_lg: 'form-p-input-lg form-rounded-lg form-text-lg with-floating:form-p-input-floating-lg',
    inputWrapper: 'relative',
    inputPlaceholder: 'absolute left-0 top-0 form-color-placeholder pointer-events-none',
    inputPlaceholder_sm: 'form-p-input-border-sm',
    inputPlaceholder_md: 'form-p-input-border',
    inputPlaceholder_lg: 'form-p-input-border-lg',
    inputCaret: 'mask-bg mask-form-caret form-bg-icon w-2.5 h-4 py-px box-content absolute right-0 top-1/2 transform -translate-y-1/2 z-10 transition-transform transform pointer-events-none',
    inputCaret_sm: 'form-mr-input-sm',
    inputCaret_md: 'form-mr-input',
    inputCaret_lg: 'form-mr-input-lg',
    select: {
      ...select,
      singleLabel: 'flex items-center h-full max-w-full absolute left-0 top-0 pointer-events-none bg-transparent box-border',
      singleLabel_sm: 'form-pl-input-sm form-pr-select-label-sm',
      singleLabel_md: 'form-pl-input form-pr-select-label',
      singleLabel_lg: 'form-pl-input-lg form-pr-select-label-lg with-floating:form-p-input-floating-lg',
      singleLabelText: 'overflow-ellipsis overflow-hidden block whitespace-nowrap max-w-full',
      $singleLabel: (classes, { Size }) => ([
        classes.select.singleLabel,
        classes.select[`singleLabel_${Size}`],
      ]),
    },
    $input: (classes, { isDisabled, Size, isSuccess, isDanger }) => ([
      classes.input,
      classes[`input_${Size}`],
      isDisabled ? classes.input_disabled : null,
      !isDisabled && !isSuccess && !isDanger ? classes.input_enabled : null,
      !isDisabled && isDanger ? classes.input_danger : null,
      !isDisabled && isSuccess ? classes.input_success : null,
    ]),
    $inputWrapper: (classes, { Size }) => ([
      classes.inputWrapper,
      classes[`inputWrapper_${Size}`],
    ]),
    $inputPlaceholder: (classes, { Size }) => ([
      classes.inputPlaceholder,
      classes[`inputPlaceholder_${Size}`],
    ]),
    $inputCaret: (classes, { Size }) => ([
      classes.inputCaret,
      classes[`inputCaret_${Size}`],
    ]),
  },
  SliderElement: {
    container: '',
    wrapper: '',
    wrapper_sm: 'mt-3.5',
    wrapper_md: 'mt-4',
    wrapper_lg: 'mt-5',
    slider: {
      target: 'relative box-border user-select-none touch-none tap-highlight-transparent touch-callout-none disabled:cursor-not-allowed disabled:opacity-50',
      focused: 'slider-focused',
      tooltipFocus: 'slider-tooltip-focus',
      tooltipDrag: 'slider-tooltip-drag',
      ltr: 'slider-ltr',
      rtl: 'slider-rtl',
      horizontal: 'slider-horizontal form-h-slider-horizontal',
      vertical: 'slider-vertical form-w-slider-vertical',
      vertical_sm: 'form-h-slider-vertical-sm',
      vertical_md: 'form-h-slider-vertical',
      vertical_lg: 'form-h-slider-vertical-lg',
      textDirectionRtl: 'slider-txt-rtl',
      textDirectionLtr: 'slider-txt-ltr',
      base: 'form-shadow-input w-full h-full relative z-1 form-bg-passive',
      base_sm: 'form-rounded-slider-sm',
      base_md: 'form-rounded-slider',
      base_lg: 'form-rounded-slider-lg',
      connects: 'w-full h-full relative overflow-hidden z-0 form-rounded-slider',
      connects_sm: 'form-rounded-slider-sm',
      connects_md: 'form-rounded-slider',
      connects_lg: 'form-rounded-slider-lg',
      connect: 'absolute z-1 top-0 right-0 transform-origin-0 transform-style-flat h-full w-full form-bg-primary cursor-pointer tap:duration-300 tap:transition-transform disabled:cursor-not-allowed',
      connect_sm: 'form-rounded-slider-sm',
      connect_md: 'form-rounded-slider',
      connect_lg: 'form-rounded-slider-lg',
      origin: 'slider-origin absolute z-1 top-0 right-0 transform-origin-0 transform-style-flat h-full w-full h:h-0 v:-top-full txt-rtl-h:left-0 txt-rtl-h:right-auto v:w-0 tap:duration-300 tap:transition-transform',
      handle: 'absolute rounded-full border-0 cursor-grab txt-rtl-h:-left-2 txt-rtl-h:right-auto disabled:cursor-not-allowed disabled:pointer-events-none form-bg-slider-handle form-shadow-slider-handle hover:form-shadow-slider-handle-hover focus:form-shadow-slider-handle-focus focus:outline-zero focus:form-ring',
      handle_sm: 'form-size-slider-handle-sm h:form-top-slider-handle-horizontal-sm h:form-right-slider-handle-horizontal-sm v:form-bottom-slider-handle-vertical-sm v:form-right-slider-handle-vertical-sm',
      handle_md: 'form-size-slider-handle h:form-top-slider-handle-horizontal h:form-right-slider-handle-horizontal v:form-bottom-slider-handle-vertical v:form-right-slider-handle-vertical',
      handle_lg: 'form-size-slider-handle-lg h:form-top-slider-handle-horizontal-lg h:form-right-slider-handle-horizontal-lg v:form-bottom-slider-handle-vertical-lg v:form-right-slider-handle-vertical-lg',
      handleUpper: 'slider-handle-upper',
      handleLower: 'slider-handle-lower',
      touchArea: 'h-full w-full',
      tooltip: 'absolute block font-semibold whitespace-nowrap min-w-5 text-center border form-border-color-slider-tooltip form-bg-primary form-color-on-primary transform tt-focus:hidden tt-focused:block tt-drag:hidden tt-dragging:block h:-translate-x-1/2 h:left-1/2 v:-translate-y-1/2 v:top-1/2 merge-h:translate-x-1/2 merge-v:translate-y-1/2 merge-h:left-auto merge-v:top-auto',
      tooltip_sm: 'form-text-small-sm form-py-slider-tooltip-sm form-px-slider-tooltip-sm form-rounded-small-sm',
      tooltip_md: 'form-text-small form-py-slider-tooltip form-px-slider-tooltip form-rounded-small',
      tooltip_lg: 'form-text-small-lg form-py-slider-tooltip-lg form-px-slider-tooltip-lg form-rounded-small-lg',
      tooltipTop: 'h:arrow-bottom',
      tooltipTop_sm: 'form-bottom-slider-tooltip-top-sm merge-h:form-bottom-slider-tooltip-top-merged-sm',
      tooltipTop_md: 'form-bottom-slider-tooltip-top merge-h:form-bottom-slider-tooltip-top-merged',
      tooltipTop_lg: 'form-bottom-slider-tooltip-top-lg merge-h:form-bottom-slider-tooltip-top-merged-lg',
      tooltipBottom: ' h:arrow-top',
      tooltipBottom_sm: 'form-top-slider-tooltip-bottom-sm merge-h:form-top-slider-tooltip-bottom-merged-sm',
      tooltipBottom_md: 'form-top-slider-tooltip-bottom merge-h:form-top-slider-tooltip-bottom-merged',
      tooltipBottom_lg: 'form-top-slider-tooltip-bottom-lg merge-h:form-top-slider-tooltip-bottom-merged-lg',
      tooltipLeft: 'v:arrow-right',
      tooltipLeft_sm: 'form-right-slider-tooltip-left-sm merge-v:form-right-slider-tooltip-left-merged-sm',
      tooltipLeft_md: 'form-right-slider-tooltip-left merge-v:form-right-slider-tooltip-left-merged',
      tooltipLeft_lg: 'form-right-slider-tooltip-left-lg merge-v:form-right-slider-tooltip-left-merged-lg',
      tooltipRight: 'v:arrow-left',
      tooltipRight_sm: 'form-left-slider-tooltip-right-sm merge-v:form-left-slider-tooltip-right-merged-sm',
      tooltipRight_md: 'form-left-slider-tooltip-right merge-v:form-left-slider-tooltip-right-merged',
      tooltipRight_lg: 'form-left-slider-tooltip-right-lg merge-v:form-left-slider-tooltip-right-merged-lg',
      tooltipHidden: 'slider-tooltip-hidden',
      active: 'slider-active cursor-grabbing',
      draggable: 'cursor-ew-resize v:cursor-ns-resize',
      tap: 'slider-state-tap',
      drag: 'slider-state-drag',
      $vertical: (classes, { Size }) => ([
        classes.slider.vertical,
        classes.slider[`vertical_${Size}`],
      ]),
      $base: (classes, { Size }) => ([
        classes.slider.base,
        classes.slider[`base_${Size}`],
      ]),
      $connects: (classes, { Size }) => ([
        classes.slider.connects,
        classes.slider[`connects_${Size}`],
      ]),
      $connect: (classes, { Size }) => ([
        classes.slider.connect,
        classes.slider[`connect_${Size}`],
      ]),
      $handle: (classes, { Size }) => ([
        classes.slider.handle,
        classes.slider[`handle_${Size}`],
      ]),
      $tooltip: (classes, { Size }) => ([
        classes.slider.tooltip,
        classes.slider[`tooltip_${Size}`],
      ]),
      $tooltipTop: (classes, { Size }) => ([
        classes.slider.tooltipTop,
        classes.slider[`tooltipTop_${Size}`],
      ]),
      $tooltipBottom: (classes, { Size }) => ([
        classes.slider.tooltipBottom,
        classes.slider[`tooltipBottom_${Size}`],
      ]),
      $tooltipLeft: (classes, { Size }) => ([
        classes.slider.tooltipLeft,
        classes.slider[`tooltipLeft_${Size}`],
      ]),
      $tooltipRight: (classes, { Size }) => ([
        classes.slider.tooltipRight,
        classes.slider[`tooltipRight_${Size}`],
      ]),
    },
    $wrapper: (classes, { Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
    ]),
  },
  StaticElement: {
    container: '',
    content: '',
    content_sm: 'form-pt-input-border-sm form-text-sm',
    content_md: 'form-pt-input-border form-text',
    content_lg: 'form-pt-input-border-lg form-text-lg',
    $content: (classes, { Size }) => ([
      classes.content,
      classes[`content_${Size}`],
    ]),
  },
  TagsElement: {
    container: '',
    select: {
      ...select,
      tags: 'flex-grow flex-shrink flex flex-wrap items-center mt-1',
      tags_sm: 'form-pl-input-y-sm',
      tags_md: 'form-pl-input-y',
      tags_lg: 'form-pl-input-y-lg with-floating:form-p-input-floating-lg',
      tag: 'form-bg-tag form-color-tag form-border-tag form-border-color-tag font-semibold mr-1 mb-1 flex items-center whitespace-nowrap',
      tag_sm: 'form-rounded-tag-sm form-text-small-sm form-py-tag-sm form-pl-tag-sm',
      tag_md: 'form-rounded-tag form-text-small form-py-tag form-pl-tag',
      tag_lg: 'form-rounded-tag-lg. form-text-small-lg form-py-tag-lg form-pl-tag-lg',
      tagDisabled: 'opacity-50',
      tagDisabled_sm: 'form-pr-tag-sm',
      tagDisabled_md: 'form-pr-tag',
      tagDisabled_lg: 'form-pr-tag-lg',
      tagRemove: 'flex items-center justify-center p-1 mx-0.5 hover:bg-black hover:bg-opacity-10 group',
      tagRemove_sm: 'form-rounded-tag-sm',
      tagRemove_md: 'form-rounded-tag',
      tagRemove_lg: 'form-rounded-tag-lg',
      tagRemoveIcon: 'mask-bg mask-form-remove bg-current inline-block w-3 h-3',
      tagsSearchWrapper: 'inline-block relative mx-1 mb-1 flex-grow flex-shrink h-full',
      tagsSearch: 'absolute bg-transparent form-color-input inset-0 border-0 outline-zero appearance-none p-0 box-border w-full',
      tagsSearch_sm: 'form-text-sm',
      tagsSearch_md: 'form-text',
      tagsSearch_lg: 'form-text-lg',
      tagsSearchCopy: 'invisible whitespace-pre-wrap inline-block h-px',
      $tags: (classes, { Size }) => ([
        classes.select.tags,
        classes.select[`tags_${Size}`],
      ]),
      $tag: (classes, { Size }) => ([
        classes.select.tag,
        classes.select[`tag_${Size}`],
      ]),
      $tagDisabled: (classes, { Size }) => ([
        classes.select.tagDisabled,
        classes.select[`tagDisabled_${Size}`],
      ]),
      $tagRemove: (classes, { Size }) => ([
        classes.select.tagRemove,
        classes.select[`tagRemove_${Size}`],
      ]),
      $tagsSearch: (classes, { Size }) => ([
        classes.select.tagsSearch,
        classes.select[`tagsSearch_${Size}`],
      ]),
    }
  },
  TextareaElement: {
    ...textarea,
  },
  TextElement: {
    ...text,
  },
  ToggleElement: {
    container: '',
    wrapper: 'form-pt-input-border flex items-center',
    text: 'ml-2',
    toggle: {
      container: 'form-shadow-input inline-block rounded-full outline-zero transition-input ease-in-out focus:form-ring',
      container_enabled: 'hover:form-shadow-input-hover focus:form-shadow-input-focus',
      container_disabled: 'cursor-not-allowed opacity-50',
      toggle: 'flex rounded-full relative cursor-pointer transition-colors items-center box-content border-2 leading-none',
      toggle_sm: 'form-w-toggle-sm form-h-toggle-sm text-xs',
      toggle_md: 'form-w-toggle form-h-toggle text-xs',
      toggle_lg: 'form-w-toggle-lg form-h-toggle-lg text-0.5sm',
      toggleOn: 'form-bg-primary form-border-color-primary justify-start form-color-on-primary',
      toggleOff: 'form-bg-passive form-border-color-passive form-color-passive justify-end',
      toggleOnDisabled: 'form-bg-primary form-border-color-primary justify-start form-color-on-primary',
      toggleOffDisabled: 'form-bg-passive form-border-color-passive form-color-passive justify-end',
      handle: 'inline-block form-bg-toggle-handle top-0 rounded-full absolute transition-all',
      handle_sm: 'form-size-toggle-handle-sm',
      handle_md: 'form-size-toggle-handle',
      handle_lg: 'form-size-toggle-handle-lg',
      handleOn: 'left-full transform -translate-x-full',
      handleOff: 'left-0',
      handleOnDisabled: 'left-full transform -translate-x-full',
      handleOffDisabled: 'left-0',
      label: 'text-center border-box whitespace-nowrap select-none',
      label_sm: 'form-w-toggle-label-sm',
      label_md: 'form-w-toggle-label',
      label_lg: 'form-w-toggle-label-lg',
      $container: (classes, { Size, isDisabled }) => ([
        classes.toggle.container,
        classes.toggle[`container_${Size}`],
        !isDisabled ? classes.toggle.container_enabled : classes.toggle.container_disabled,
      ]),
      $toggle: (classes, { Size }) => ([
        classes.toggle.toggle,
        classes.toggle[`toggle_${Size}`],
      ]),
      $handle: (classes, { Size }) => ([
        classes.toggle.handle,
        classes.toggle[`handle_${Size}`],
      ]),
      $label: (classes, { Size }) => ([
        classes.toggle.label,
        classes.toggle[`label_${Size}`],
      ]),
    }
  },
  TTextareaElement: {
    ...textarea,
  },
  TTextElement: {
    ...text,
  },
  TEditorElement: {
    ...editor,
  },

  // Wrappers
  DatepickerWrapper: {
    datepicker: '',
    calendarContainer: ''
  },
  EditorWrapper: {
    container: 'form-bg-input form-color-input',
  },

  // Components
  ElementAddon: {
    container: 'form-bg-addon form-color-addon flex items-center justify-center flex-grow-0 flex-shrink-0',
    container_before: '',
    container_after: 'order-2',
    container_sm: '',
    container_md: '',
    container_lg: '',
    container_before_sm: 'form-rounded-l-sm form-pl-input-sm form-pr-space-addon-sm',
    container_before_md: 'form-rounded-l form-pl-input form-pr-space-addon',
    container_before_lg: 'form-rounded-l-lg form-pl-input-lg form-pr-space-addon-lg',
    container_after_sm: 'form-rounded-r-sm form-pr-input-sm form-pl-space-addon-sm',
    container_after_md: 'form-rounded-r form-pr-input form-pl-space-addon',
    container_after_lg: 'form-rounded-r-lg form-pr-input-lg form-pl-space-addon-lg',
    wrapper: 'flex items-center justify-center',
    $container: (classes, { type, Size }) => ([
      classes.container,
      classes[`container_${Size}`],
      classes[`container_${type}`],
      classes[`container_${type}_${Size}`],
    ]),
  },
  ElementDescription: {
    container: 'form-color-muted',
    container_sm: 'form-text-small-sm mt-0.5',
    container_md: 'form-text-small mt-1',
    container_lg: 'form-text-small-lg mt-1',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  ElementError: {
    container: 'form-color-danger block',
    container_sm: 'form-text-small-sm mt-0.5',
    container_md: 'form-text-small mt-1',
    container_lg: 'form-text-small-lg mt-1',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  ElementInfo: {
    container: 'inline-block w-3.5 h-3.5 form-bg-info relative ml-1 top-px cursor-pointer group h-full',
    wrapper: 'absolute left-5 -top-0.5 -mt-px opacity-0 invisible group-hover:opacity-100 group-hover:form-visible transition z-20 w-52',
    content: 'bg-black bg-opacity-90 text-white rounded-md form-small-font-size py-1 px-2.5 not-italic inline-block relative',
  },
  ElementLabel: {
    container: 'flex items-center',
    container_sm: 'form-pr-gutter-sm',
    container_md: 'form-pr-gutter',
    container_lg: 'form-pr-gutter-lg',
    $container: (classes, { el$, Size }) => ([
      classes.container,
      classes[`container_${Size}`],
      !el$.inline ? el$.columnsClasses.label : null,
    ]),
  },
  ElementLabelFloating: {
    container: 'label-floating relative pointer-events-none',
    label: 'absolute z-10 leading-px text-0.5xs px-px -form-top-border-width-input-t transition whitespace-nowrap form-color-muted',
    label_enabled: 'form-bg-input',
    label_disabled: 'form-bg-disabled',
    label_danger: 'form-bg-input-danger',
    label_success: 'form-bg-input-success',
    label_sm: 'form-left-input-sm',
    label_md: 'form-left-input',
    label_lg: 'form-left-input-lg mt-2.5',
    label_invisible: 'opacity-0 invisible',
    label_visible: 'opacity-100 visible',
    $label: (classes, { visible, Size, el$ }) => ([
      classes.label,
      classes[`label_${Size}`],
      visible ? classes.label_visible : classes.label_invisible,
      !el$.isDisabled && !el$.isDanger && !el$.isSuccess ? classes.label_enabled : null,
      el$.isDisabled ? classes.label_disabled : null,
      el$.isDanger ? classes.label_danger : null,
      el$.isSuccess ? classes.label_success : null,
    ]),
  },
  ElementLayout: {
    container: '',
    container_sm: 'form-text-sm',
    container_md: 'form-text',
    container_lg: 'form-text-lg',
    container_error: 'has-error',
    outerWrapper: 'grid grid-cols-12',
    outerWrapper_sm: 'form-gap-x-gutter-sm',
    outerWrapper_md: 'form-gap-x-gutter',
    outerWrapper_lg: 'form-gap-x-gutter-lg',
    outerWrapper_single: '!gap-0',
    outerWrapper_single_sm: '',
    outerWrapper_single_md: '',
    outerWrapper_single_lg: '',
    outerWrapper_multiple: '',
    outerWrapper_multiple_sm: '',
    outerWrapper_multiple_md: '',
    outerWrapper_multiple_lg: '',
    innerContainer: 'flex-1',
    innerWrapperBefore: 'w-full',
    innerWrapper: '',
    innerWrapperAfter: 'w-full',
    $container: (classes, { el$, Size }) => ([
      classes.container,
      classes[`container_${Size}`],
      el$.columnsClasses.container,
      el$.classes.container,
      !el$.isStatic && el$.errors && !!el$.errors.length ? classes.container_error : null
    ]),
    $innerContainer:  (classes, { el$ }) => ([
      classes.innerContainer,
      el$.columnsClasses.innerContainer,
    ]),
    $innerWrapper:  (classes, { el$ }) => ([
      classes.innerWrapper,
      el$.columnsClasses.wrapper,
    ]),
    $outerWrapper:  (classes, { multiple, Size }) => ([
      classes.outerWrapper,
      classes[`outerWrapper_${Size}`],
      multiple ? classes.outerWrapper_multiple : classes.outerWrapper_single,
      multiple ? classes[`outerWrapper_multiple_${Size}`] : classes[`outerWrapper_single_${Size}`],
    ]),
  },
  ElementLayoutInline: {
    container: 'flex',
    container_error: 'has-error',
    $container: (classes, { el$ }) => ([
      classes.container,
      !el$.isStatic && el$.errors && !!el$.errors.length ? classes.container_error : null
    ]),
  },
  ElementLoader: {
    container: 'relative z-10 order-1',
    loader: 'absolute w-4 h-4 right-full mask-bg mask-form-spinner form-bg-primary animate-spin',
    loader_sm: 'form-top-input-border-sm form-mr-input-sm mt-0.5',
    loader_md: 'form-top-input-border form-mr-input mt-1',
    loader_lg: 'form-top-input-border-lg form-mr-input-lg mt-1',
    $loader: (classes, { Size }) => ([
      classes.loader,
      classes[`loader_${Size}`],
    ]),
  },
  ElementMessage: {
    container: 'form-color-success block',
    container_sm: 'form-text-small-sm mt-0.5',
    container_md: 'form-text-small mt-1',
    container_lg: 'form-text-small-lg mt-1',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  ElementText: {
    container: '',
    container_before: '',
    container_between: '',
    container_after: '',
    $container: (classes, { type }) => ([
      classes.container,
      classes[`container_${type}`]
    ]),
  },
  FormElements: {
    container: 'grid grid-cols-12',
    container_sm: 'form-gap-x-gutter-sm',
    container_md: 'form-gap-x-gutter',
    container_lg: 'form-gap-x-gutter-lg',
    $container: (classes, { type }) => ([
      classes.container,
      classes[`container_${type}`]
    ]),
  },
  FormErrors: {
    container: 'form-bg-danger form-color-danger rounded',
    container_sm: 'form-rounded-sm form-text-sm form-mb-gutter-sm py-2 px-3',
    container_md: 'form-rounded form-text form-mb-gutter py-2 px-3',
    container_lg: 'form-rounded-lg form-text-lg form-mb-gutter-lg py-3 px-4',
    error: '',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ])
  },
  FormLanguage: {
    container: 'flex-grow flex-shrink w-full',
    wrapper: 'block border-b-2 text-center',
    wrapper_active: 'form-border-color-primary',
    wrapper_inactive: 'border-transparent',
    wrapper_valid: '',
    wrapper_invalid: 'form-color-danger form-border-color-danger',
    wrapper_sm: 'py-1.5 px-3.5',
    wrapper_md: 'py-2 px-4',
    wrapper_lg: 'py-2 px-4',
    $wrapper: (classes, { selected, Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
      selected ? classes.wrapper_active : classes.wrapper_inactive
    ]),
  },
  FormLanguages: {
    container: 'flex items-center justify-between',
    container_sm: 'form-mb-gutter form-text-sm',
    container_md: 'form-mb-gutter-lg form-text',
    container_lg: 'form-mb-gutter-lg form-text-lg',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  FormMessages: {
    container: 'form-bg-success form-color-success',
    container_sm: 'form-rounded-sm form-text-sm form-mb-gutter-sm py-2 px-3',
    container_md: 'form-rounded form-text form-mb-gutter py-2 px-3',
    container_lg: 'form-rounded-lg form-text-lg form-mb-gutter-lg py-3 px-4',
    message: '',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ])
  },
  FormStep: {
    container: 'form-step',
    wrapper: '',
    container_active: 'form-step-active',
    container_inactive: '',
    container_invalid: 'has-errors',
    container_valid: '',
    container_disabled: 'form-step-disabled',
    container_enabled: '',
    container_completed: 'form-step-completed',
    container_incompleted: '',
    container_pending: 'form-step-pending',
    $container: (classes, { active, isDisabled, completed, invalid, pending }) => ([
      classes.container,
      active ? classes.container_active : classes.container_inactive,
      isDisabled ? classes.container_disabled : classes.container_enabled,
      completed ? classes.container_completed : classes.container_incompleted,
      invalid ? classes.container_invalid : classes.container_valid,
      pending ? classes.container_pending : null,
    ]),
  },
  FormSteps: {
    container: 'flex justify-between overflow-x-auto pt-5',
    container_sm: 'form-mb-gutter form-text-sm',
    container_md: 'form-mb-gutter-lg form-text',
    container_lg: 'form-mb-gutter-lg form-text-lg',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  FormStepsControl: {
    button: 'form-border-btn form-shadow-btn focus:form-ring focus:outline-zero disabled:pointer-events-none disabled:opacity-60 disabled:cursor-not-allowed',
    button_previous_enabled: 'form-bg-btn-secondary form-color-secondary form-border-color-btn-secondary transition-transform transform hover:scale-105',
    button_previous_disabled: 'form-bg-btn-secondary form-color-secondary form-border-color-btn-secondary opacity-60 pointer-events-none',
    button_next_enabled: 'form-bg-primary form-color-on-primary form-border-color-btn transition-transform transform hover:scale-105',
    button_next_disabled: 'form-bg-primary form-color-on-primary form-border-color-btn opacity-60 pointer-events-none cursor-not-allowed',
    button_next_loading: 'form-bg-primary form-color-on-primary form-border-color-btn form-bg-spinner-on-primary',
    button_finish_enabled: 'form-bg-primary form-color-on-primary form-border-color-btn transition-transform transform hover:scale-105',
    button_finish_disabled: 'form-bg-primary form-color-on-primary form-border-color-btn opacity-60 pointer-events-none cursor-not-allowed',
    button_finish_loading: 'form-bg-primary form-color-on-primary form-border-color-btn form-bg-spinner-on-primary',
    button_sm: 'form-p-btn-sm form-rounded-btn-sm form-text-sm',
    button_md: 'form-p-btn form-rounded-btn form-tex',
    button_lg: 'form-p-btn-lg form-rounded-btn-lg form-text-lg',
    $button: (classes, { isDisabled, isLoading, type, Size }) => ([
      classes.button,
      classes[`button_${Size}`],
      isDisabled ? classes[`button_${type}_disabled`] : classes[`button_${type}_enabled`],
      isLoading ? classes[`button_${type}_loading`] : null,
    ]),
  },
  FormStepsControls: {
    container: 'flex justify-between',
    container_sm: 'form-mt-gutter form-text-sm',
    container_md: 'form-mt-gutter-lg form-text',
    container_lg: 'form-mt-gutter-lg form-text-lg',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  FormTab: {
    container: '',
    wrapper: 'block border-b-2',
    wrapper_active: 'form-border-color-primary',
    wrapper_inactive: 'border-transparent',
    wrapper_valid: '',
    wrapper_invalid: 'form-color-danger form-border-color-danger',
    wrapper_sm: 'py-1.5 px-3.5',
    wrapper_md: 'py-2 px-4',
    wrapper_lg: 'py-2 px-4',
    $container: (classes, {}) => ([
      classes.container,
    ]),
    $wrapper: (classes, { active, invalid, Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
      active ? classes.wrapper_active : classes.wrapper_inactive,
      invalid ? classes.wrapper_invalid : classes.wrapper_valid,
    ]),
  },
  FormTabs: {
    container: 'flex items-end',
    container_sm: 'form-mb-gutter form-text-sm',
    container_md: 'form-mb-gutter-lg form-text',
    container_lg: 'form-mb-gutter-lg form-text-lg',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
  },
  Vueform: {
    form: '',
  },

  // Slots
  CheckboxgroupCheckbox: {
    ...checkbox,
    container: 'flex align-start cursor-pointer',
    text: '',
    input: checkbox.input + ' form-shadow-input focus:form-ring',
    input_sm: checkbox.input_sm + ' mt-0.75',
    input_md: checkbox.input_md + ' mt-1',
    input_lg: checkbox.input_lg + ' mt-1',
  },
  CheckboxgroupCheckbox_tabs: {
    ...groupTabs,
    $wrapper: (classes, { index, items, el$, value, isDisabled, Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
      index < Object.keys(items).length - 1 ? classes.wrapper_not_last : null,
      index === 0 ? classes.wrapper_first : null,
      index === 0 ? classes[`wrapper_first_${Size}`] : null,
      index === Object.keys(items).length - 1 ? classes.wrapper_last : null,
      index === Object.keys(items).length - 1 ? classes[`wrapper_last_${Size}`] : null,
      el$.value.indexOf(value) !== -1 ? classes.wrapper_selected : classes.wrapper_unselected,
      isDisabled ? classes.wrapper_disabled : null,
    ])
  },
  CheckboxgroupCheckbox_blocks: {
    ...checkbox,
    ...groupBlocks,
    $wrapper: (classes, { index, items, el$, value, isDisabled, Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
      index < Object.keys(items).length - 1 ? classes.wrapper_not_last : null,
      index === 0 ? classes.wrapper_first : null,
      index === 0 ? classes[`wrapper_first_${Size}`] : null,
      index === Object.keys(items).length - 1 ? classes.wrapper_last : null,
      index === Object.keys(items).length - 1 ? classes[`wrapper_last_${Size}`] : null,
      el$.value.indexOf(value) !== -1 ? classes.wrapper_selected : classes.wrapper_unselected,
      isDisabled ? classes.wrapper_disabled : null,
    ]),
    $description: (classes, { Size }) => ([
      classes.description,
      classes[`description_${Size}`],
    ]),
  },
  DragAndDrop: {
    container: 'form-shadow-input form-bg-input form-color-input form-border-input border-dashed w-full transition inline-flex flex-col items-center justify-center p-6 cursor-pointer',
    container_sm: 'form-rounded-large-sm',
    container_md: 'form-rounded-large',
    container_lg: 'form-rounded-large-lg',
    container_inactive: 'form-border-color-input',
    container_active: 'form-border-color-primary',
    container_enabled: '',
    container_disabled: 'opacity-50 cursor-not-allowed',
    icon: 'inline-block w-9 h-8 mask-bg mask-form-inbox-in form-bg-primary',
    title: 'font-semibold mt-3',
    description: '',
    $container: (classes, { dragging, disabled, Size }) => ([
      classes.container,
      classes[`container_${Size}`],
      dragging ? classes.container_active : classes.container_inactive,
      disabled ? classes.container_disabled : classes.container_enabled,
    ]),
  },
  FilePreview: {
    container: 'flex justify-start flex-row group relative',
    container_sm: 'form-py-input-border-sm form-h-input-height-sm',
    container_md: 'form-py-input-border form-h-input-height',
    container_lg: 'form-py-input-border-lg form-h-input-height',
    wrapper: 'flex justify-between items-center w-full',
    file: 'flex items-center',
    filenameLink: 'hover:underline',
    filenameStatic: '',
    actions: 'flex items-center',
    percent: 'flex justify-between items-center text-sm form-color-muted group-hover:form-hidden',
    upload: 'form-bg-primary form-color-on-primary form-rounded-small text-xs py-0.5 px-1.5 ml-1.5 whitespace-nowrap transition-transform transform hover:scale-105 focus:form-ring',
    progressBar: 'form-bg-passive h-0.75 absolute bottom-0 w-full',
    progress: 'w-0 form-bg-primary transition-all ease-out duration-500 h-0.75',
    warning: 'flex w-4 h-4 items-center justify-center form-bg-danger rounded-full group-hover:form-hidden',
    warningIcon: 'mask-bg mask-form-exclamation-solid form-bg-danger-color mask-size-2.5 block w-full h-full',
    uploaded: 'flex w-4 h-4 items-center justify-center form-bg-success rounded-full group-hover:form-hidden',
    uploadedIcon: 'mask-bg mask-form-check-solid form-bg-success-color mask-size-2.5 block w-full h-full',
    remove: 'flex w-4 h-4 items-center justify-center form-bg-passive form-color-passive rounded-full transition filter hover:brightness-90 form-hidden group-hover:form-inline-block',
    removeIcon: 'mask-bg mask-form-remove-light bg-black mask-size-3 block w-full h-full',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ])
  },
  FilePreview_image: {
    container: 'flex justify-start flex-row group relative',
    wrapper: 'flex justify-between items-center w-full',
    image: 'form-shadow-input flex items-center form-bg-passive flex-grow-0 flex-shrink-0',
    image_link: '',
    image_static: '',
    image_sm: 'form-rounded-image-sm',
    image_md: 'form-rounded-image',
    image_lg: 'form-rounded-image-lg',
    img: 'form-w-input-height form-h-input-height form-hide-empty-img object-cover',
    img_sm: 'form-w-input-height-sm form-h-input-height-sm form-rounded-image-sm',
    img_md: 'form-w-input-height form-h-input-height form-rounded-image',
    img_lg: 'form-w-input-height-lg form-h-input-height-lg form-rounded-image-lg',
    file: 'flex items-center flex-grow flex-shrink ml-2.5',
    filenameLink: 'hover:underline',
    filenameStatic: '',
    actions: 'flex items-center',
    percent: 'flex justify-between items-center text-sm form-color-muted group-hover:form-hidden',
    upload: 'form-bg-primary form-color-on-primary form-rounded-small text-xs py-0.5 px-1.5 ml-1.5 whitespace-nowrap transition-transform transform hover:scale-105 focus:form-ring',
    progressBar: 'form-bg-passive h-0.75 ml-2.5 absolute bottom-0 right-0',
    progressBar_sm: 'form-left-input-height-sm',
    progressBar_md: 'form-left-input-height',
    progressBar_lg: 'form-left-input-height-lg',
    progress: 'w-0 form-bg-primary transition-all ease-out duration-500 h-0.75',
    warning: 'flex w-4 h-4 items-center justify-center form-bg-danger rounded-full group-hover:form-hidden',
    warningIcon: 'mask-bg mask-form-exclamation-solid form-bg-danger-color mask-size-2.5 block w-full h-full',
    uploaded: 'flex w-4 h-4 items-center justify-center form-bg-success rounded-full group-hover:form-hidden',
    uploadedIcon: 'mask-bg mask-form-check-solid form-bg-success-color mask-size-2.5 block w-full h-full',
    remove: 'flex w-4 h-4 items-center justify-center form-bg-passive form-color-passive rounded-full transition filter hover:brightness-90 form-hidden group-hover:form-inline-block',
    removeIcon: 'mask-bg mask-form-remove-light bg-black mask-size-3 block w-full h-full',
    $image: (classes, { hasLink, Size }) => ([
      classes.image,
      classes[`image_${Size}`],
      hasLink ? classes.image_link : classes.image_static
    ]),
    $img: (classes, { Size }) => ([
      classes.img,
      classes[`img_${Size}`],
    ]),
    $progressBar: (classes, { Size }) => ([
      classes.progressBar,
      classes[`progressBar_${Size}`],
    ])
  },
  FilePreview_gallery: {
    container: 'flex justify-start flex-col transition duration-500 relative group',
    container_sm: 'form-w-gallery-sm form-h-gallery-sm',
    container_md: 'form-w-gallery form-h-gallery',
    container_lg: 'form-w-gallery-lg form-h-gallery-lg',
    image: 'form-shadow-input w-full h-full form-bg-passive',
    image_sm: 'form-rounded-gallery-sm',
    image_md: 'form-rounded-gallery',
    image_lg: 'form-rounded-gallery-lg',
    image_link: '',
    image_static: '',
    img: 'w-full h-full object-cover form-hide-empty-img',
    img_sm: 'form-rounded-gallery-sm',
    img_md: 'form-rounded-gallery',
    img_lg: 'form-rounded-gallery-lg',
    overlay: 'absolute inset-0 bg-white bg-opacity-50 transition duration-300 opacity-0 invisible flex items-center justify-center p-3 form-rounded group-hover:form-visible group-hover:opacity-100',
    overlay_sm: 'form-rounded-gallery-sm',
    overlay_md: 'form-rounded-gallery',
    overlay_lg: 'form-rounded-gallery-lg',
    upload: 'relative z-1 form-bg-primary form-color-on-primary form-rounded-small text-xs py-0.5 px-1.5 whitespace-nowrap transition-transform transform hover:scale-105 focus:form-ring',
    progressBar: 'bg-white absolute left-1 right-1 bottom-1 h-0.75',
    progress: 'w-0 form-bg-primary transition-all ease-out duration-500 h-0.75',
    warning: 'absolute right-0.5 bottom-0.5 mr-px mb-px flex w-4 h-4 items-center justify-center form-bg-danger rounded-full',
    warningIcon: 'mask-bg mask-form-exclamation-solid form-bg-danger-color mask-size-2.5 block w-full h-full',
    uploaded: 'absolute right-0.5 bottom-0.5 mr-px mb-px flex w-4 h-4 items-center justify-center form-bg-success rounded-full',
    uploadedIcon: 'mask-bg mask-form-check-solid form-bg-success-color mask-size-2.5 block w-full h-full',
    remove: 'flex w-4 h-4 items-center justify-center form-bg-passive form-color-passive absolute top-0.5 right-0.5 mt-px mr-px form-hidden rounded-full transition filter hover:brightness-90 group-hover:form-inline-block ',
    removeIcon: 'mask-bg mask-form-remove-light bg-black mask-size-3 block w-full h-full',
    $container: (classes, { Size }) => ([
      classes.container,
      classes[`container_${Size}`],
    ]),
    $image: (classes, { Size }) => ([
      classes.image,
      classes[`image_${Size}`],
    ]),
    $img: (classes, { Size }) => ([
      classes.img,
      classes[`img_${Size}`],
    ]),
    $overlay: (classes, { Size }) => ([
      classes.overlay,
      classes[`overlay_${Size}`],
    ]),
  },
  RadiogroupRadio: {
    ...radio,
    container: 'flex align-start cursor-pointer',
    text: '',
    input: radio.input + ' form-shadow-input focus:form-ring',
    input_sm: radio.input_sm + ' mt-0.75',
    input_md: radio.input_md + ' mt-1',
    input_lg: radio.input_lg + ' mt-1',
  },
  RadiogroupRadio_tabs: {
    ...groupTabs,
    $wrapper: (classes, { index, items, el$, value, isDisabled, Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
      index < Object.keys(items).length - 1 ? classes.wrapper_not_last : null,
      index === 0 ? classes.wrapper_first : null,
      index === 0 ? classes[`wrapper_first_${Size}`] : null,
      index === Object.keys(items).length - 1 ? classes.wrapper_last : null,
      index === Object.keys(items).length - 1 ? classes[`wrapper_last_${Size}`] : null,
      el$.value == value ? classes.wrapper_selected : classes.wrapper_unselected,
      isDisabled ? classes.wrapper_disabled : null,
    ])
  },
  RadiogroupRadio_blocks: {
    ...radio,
    ...groupBlocks,
    $wrapper: (classes, { index, items, el$, value, isDisabled, Size }) => ([
      classes.wrapper,
      classes[`wrapper_${Size}`],
      index < Object.keys(items).length - 1 ? classes.wrapper_not_last : null,
      index === 0 ? classes.wrapper_first : null,
      index === 0 ? classes[`wrapper_first_${Size}`] : null,
      index === Object.keys(items).length - 1 ? classes.wrapper_last : null,
      index === Object.keys(items).length - 1 ? classes[`wrapper_last_${Size}`] : null,
      el$.value == value ? classes.wrapper_selected : classes.wrapper_unselected,
      isDisabled ? classes.wrapper_disabled : null,
    ]),
    $description: (classes, { Size }) => ([
      classes.description,
      classes[`description_${Size}`],
    ]),
  },
}