export default {
  text: {
    features: [
      'addons',
      'autocomplete',
      'baseElement',
      'classes',
      'columns',
      'components',
      'conditions',
      'data',
      'debounce',
      'default',
      'description',
      'disabled',
      'empty',
      'events',
      'floating',
      'form$',
      'handleChange',
      'handleKeyup',
      'id',
      'info',
      'input',
      'inputType',
      'label',
      'layout',
      'nullValue',
      'path',
      'placeholder',
      'readonly',
      'slots',
      'theme',
      'validation',
      'value',
      'view'
    ]
  },
  group: {
    features: [
      'baseElement',
      'childrenGroup',
      'classes',
      'columns',
      'components',
      'conditions',
      'dataGroup',
      'description',
      'elements',
      'form$',
      'info',
      'label',
      'layout',
      'pathGroup',
      'slots',
      'theme',
      'validationGroup',
      'valueGroup',
      'view'
    ]
  },
  object: {
    features: [
      'baseElement',
      'childrenObject',
      'classes',
      'columns',
      'components',
      'conditions',
      'dataObject',
      'description',
      'elements',
      'form$',
      'info',
      'label',
      'layout',
      'path',
      'slots',
      'theme',
      'validationObject',
      'valueObject',
      'view'
    ]
  },
  list: {
    features: [
      'arrayType',
      'baseElement',
      'childrenList',
      'classesList',
      'columns',
      'components',
      'conditions',
      'dataList',
      // 'default',
      // 'description',
        //   'disabled',
      // 'elements',
        // 'events',
      // 'form$',
        // 'handleChangeList',
      // 'info',
      // 'label',
      // 'layout',
        // 'nullValueArray',
      // 'path',
      // 'slots',
      // 'theme',
        // 'validationList',
        // 'valueList',
      // 'view'
    ]
  },
}