export default {
  text: {
    features: [
      // 'addons',
      // 'autocomplete',
      // 'baseElement',
      // 'baseLayout',
      // 'classes',
      // 'columns',
      // 'components',
      // 'conditions',
      // 'data',
      // 'debounce',
      // 'default',
      // 'description',
      // 'disabled',
      // 'empty',
      'events',
      // 'floating',
      // 'form$',
      // 'handleChange',
      // 'handleKeyup',
      // 'id',
      // 'info',
      // 'input',
      // 'inputType',
      // 'label',
      // 'nullValue',
      // 'path',
      // 'placeholder',
      // 'readonly',
      // 'slots',
      // 'theme',
      // 'validation',
      // 'value',
      // 'view'
    ]
  },
  group: {
    features: [
      'baseElement',
      'childrenValidation',
      'classes',
      'columns',
      'components',
      'conditions',
      'description',
      'elements',
      'form$',
      'groupData',
      'info',
      'label',
      'nestedLayout',
      'nestedValue',
      'path',
      'schemaChildren',
      'slots',
      'theme',
      'view'
    ]
  },
}