export default {
  text: {
    features: [
      'addons',
      'autocomplete',
      'baseElement',
      'baseLayout',
      'classes',
      'columns',
      'components',
      'conditions',
      'data',
      'debounce',
      'description',
      'disabled',
      'empty',
      'events',
      'floating',
      'form$',
      'handleChange',
      'handleKeyup',
      'id',
      'info',
      'input',
      'inputType',
      'label',
      'path',
      'placeholder',
      'readonly',
      'slots',
      'theme',
      'validation',
      'value',
      'view'
    ]
  }}