module.exports = {
  default: 'input field',
  AddressElement: 'address group',
  ButtonElement: 'button',
  CheckboxElement: 'checkbox',
  CheckboxgroupElement: 'checkbox group',
  FileElement: 'file',
  GroupElement: 'group',
  HiddenElement: 'hidden input',
  ListElement: 'list',
  MultifileElement: 'file list',
  MultiselectElement: 'multiselect',
  ObjectElement: 'object group',
  RadioElement: 'radio',
  RadiogroupElement: 'radio group',
  SelectElement: 'select',
  SliderElement: 'slider',
  StaticElement: 'static content',
  TagsElement: 'tags input',
  TextareaElement: 'textarea',
  ToggleElement: 'toggle',
  TrixElement: 'trix editor',
  TTextareaElement: 'textarea',
  TTrixElement: 'trix editor',
}